version: "3.8"

services:
  api.redis:
    image: redis:latest
    container_name: api.redis
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: always
    networks:
      - pubsub
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  api.db:
    image: postgres:latest
    restart: always
    container_name: api.db
    shm_size: 128mb
    healthcheck:
      interval: 10s
      retries: 10
      test: 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
      timeout: 2s
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgresql_db:/var/lib/postgresql/data

    networks:
      - postgresql_networks

volumes:
  postgresql_db:

networks:
  pubsub:
    driver: bridge
  postgresql_networks:
    driver: bridge
